### ISSUE TITLE
Does not install on python 2.6

### ISSUE THREAD

**Issue by ErikWallin** [apiaryio/snowcrash#308]
I use CentOS 6.6 (in a Vagrant box), which has python 2.6.6. I get an installation error. The configure script use functionality only available in 2.7. sys.version_info only became a named tuple in 2.7. To get this to work in 2.6, it needs to be accessed as a regular tuple

sys.version_info[0] != 2.

The commit that caused this was aaf67e700f6ed51b28120f4e5be7681c8241c501 (Mar 11, 2015)

==> default: Notice: /Stage[main]/Snowcrash/Exec[snowcrash-install]/returns: python ./configure
==> default: Notice: /Stage[main]/Snowcrash/Exec[snowcrash-install]/returns: Traceback (most recent call last):
==> default: Notice: /Stage[main]/Snowcrash/Exec[snowcrash-install]/returns:   File "./configure", line 12, in <module>
==> default: Notice: /Stage[main]/Snowcrash/Exec[snowcrash-install]/returns:     if sys.version_info.major != 2:
==> default: Notice: /Stage[main]/Snowcrash/Exec[snowcrash-install]/returns: AttributeError: 'tuple' object has no attribute 'major'
==> default: Notice: /Stage[main]/Snowcrash/Exec[snowcrash-install]/returns: make: *** [config.gypi] Error 1

**Comment by zdne** [comment]
@kylef can you please look into this? As I am not as familiar with Python – how hard it would be for us to support 2.6? If we can't support it I would clearly state it in requirements.

**Comment by kylef** [comment]
This was fixed in 7f98bdac9bd96856260b26eaf4e4f65e3088f1a9.
